"""Generate worker_config.yaml for the installed worker."""

import os
import logging

from ..catalog.models import ModelInfo

logger = logging.getLogger(__name__)

# Template follows the format from asr_worker/worker_config.yaml.example
_CONFIG_TEMPLATE = """\
# DiTing ASR Worker Configuration
# Generated by DiTing Worker Manager

engine: {engine}
port: {port}
device: "{device}"
max_concurrency: 1

server_url: {server_url}
advertise_url: {advertise_url}
shared_paths: []
temp_upload_dir: "temp_uploads"
model_base_path: "{model_base_path}"

models:
{models_section}
"""

_SENSEVOICE_SECTION = """\
  sensevoice:
    model_id: "{model_id}"
    vad_model: "iic/speech_fsmn_vad_zh-cn-16k-common-pytorch"
    vad_max_segment_time: 30000
    cache_dir: null
"""

_WHISPER_SECTION = """\
  whisper:
    model_name: "{model_name}"
    download_root: null
"""

_QWEN3ASR_SECTION = """\
  qwen3asr:
    model_name: "{model_name}"
    aligner_name: "Qwen/Qwen3-ForcedAligner-0.6B"
    use_aligner: true
    batch_size: 8
    max_tokens: 256
"""

_BAILIAN_SECTION = """\
  # Cloud engine — no local model config needed
"""


def write_config(
    worker_dir: str,
    engine: str,
    model: ModelInfo | None = None,
    port: int = 8001,
    device: str = "cuda:0",
    model_base_path: str = "",
    server_url: str = "",
) -> str:
    """
    Write worker_config.yaml to the worker directory.
    Returns the path to the written config file.
    """
    # Build the models section based on engine
    if engine == "sensevoice":
        model_id = model.model_id if model else "iic/SenseVoiceSmall"
        models_section = _SENSEVOICE_SECTION.format(model_id=model_id)
    elif engine == "whisper":
        model_name = (model.whisper_model_name or model.model_id) if model else "large-v3-turbo"
        models_section = _WHISPER_SECTION.format(model_name=model_name)
    elif engine == "qwen3asr":
        model_name = model.model_id if model else "Qwen/Qwen3-ASR-1.7B"
        models_section = _QWEN3ASR_SECTION.format(model_name=model_name)
    elif engine == "bailian":
        models_section = _BAILIAN_SECTION
    else:
        models_section = "  # Unknown engine"

    # Normalize path separators for YAML
    model_base_path_normalized = model_base_path.replace("\\", "/")

    # Format server_url and advertise_url for YAML
    server_url_yaml = f'"{server_url}"' if server_url else "null"
    advertise_url_yaml = "null"

    content = _CONFIG_TEMPLATE.format(
        engine=engine,
        port=port,
        device=device,
        server_url=server_url_yaml,
        advertise_url=advertise_url_yaml,
        model_base_path=model_base_path_normalized,
        models_section=models_section,
    )

    config_path = os.path.join(worker_dir, "worker_config.yaml")
    os.makedirs(worker_dir, exist_ok=True)
    with open(config_path, "w", encoding="utf-8") as f:
        f.write(content)

    logger.info(f"Worker config written to {config_path}")
    return config_path
